### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by Naios** [Naios/WIde#1]
Task List (edit this):
- [ ] Framework
  - [ ] Entities
    - [ ] Server
    - [ ] Client
  - [ ] Game
    - [ ] Add more server and client enums
  - [x] Storages
    - [x] Server Storages @Naios
      - [x] Server Storage Reading
      - [x] Server Storage Mapping
      - [x] SQL Building
      - [x] Add enums to fields
      - [x] Java Dynamic Proxy mapping based on .json
    - [x] Client Storages
      - [x] Client Storage Reading
      - [x] Client Storage Mapping
      - [x] Client Storage Auto selection
    - [x] Name Storages
    - [ ] Web Storages
- [x] Session
  - [x] Config
  - [x] Enviroment (arguments)
  - [x] Database connection
  - [x] Log4j or compareable
  - [x] Convert .properties into .json
